# Generated by Django 2.2.6 on 2019-10-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='articles.Hashtag'),
        ),
    ]
